config/routes.rb
Rails.application.routes.draw do
  root to: "travels#index"
  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       passwords: "users/passwords",
                     }
  devise_scope :user do
    post "/users/guest_sign_in", to: "users/sessions#new_guest"
  end
  resources :travels do
    resource :favorites, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favolite.rb
class Favolite < ApplicationRecord
  belongs_to :user
  belongs_to :travel
  has_many :travels, dependent: :destroy
  has_many :users, dependent: :destroy
  validates :user_id, presence: true
  validates :travel_id, presence: true, uniqueness: { scope: :user_id }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :travel, counter_cache: :favorites_count
  validates :user_id, presence: true, uniqueness: { scope: :travel_id, message: "は同じ投稿に2回以上いいねはできません" }
  validates :travel_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :travel
  validates :user_id, presence: true
  validates :travel_id, presence: true, uniqueness: { scope: :user_id }
end

app/models/travel.rb
class Travel < ApplicationRecord
  belongs_to :user
  has_many :travel_details, dependent: :destroy
  validates :country, :region, presence: true, length: { maximum: 200 }
  validates :city, length: { maximum: 200 }
  accepts_nested_attributes_for :travel_details, allow_destroy: true

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  before_save :search_lat_and_lng

  def favorited_by?(user)
    favorites.find_by(user_id: user.id).present?
  end

  def search_lat_and_lng
    search_words = "#{self.country} #{self.region} #{self.city}"
    geocoder = Geocoder.search(search_words).first
    self.latitude = geocoder.latitude
    self.longitude = geocoder.longitude
    self.country_code = geocoder.country_code
    country = ISO3166::Country.new(self.country_code)
    self.continent = country.continent.downcase.gsub(/ /, "_")

    if self.country_code == "JP"
      state = geocoder.state
      pref = JpPrefecture::Prefecture.find name: state
      self.area = Settings.area.to_h.key(pref.area).to_s
    else
      self.area = nil
    end
  end
end

app/models/travel_detail.rb
class TravelDetail < ApplicationRecord
  belongs_to :travel
  validates :image, presence: true
  validates :content, presence: true, length: { maximum: 10000 }
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :travels, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :favorited_travels, through: :favorites, source: :travel
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 30 }

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.name = "ゲスト"
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    added_attrs = [:name]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  def check_guest
    email = resource&.email || params[:user][:email].downcase
    if email == "guest@example.com"
      redirect_to root_path, alert: "ゲストユーザーの変更・削除はできません。"
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    current_user.favorites.create!(travel_id: params[:travel_id])
    @travel = Travel.find(params[:travel_id])
  end

  def destroy
    current_user.favorites.find_by(travel_id: params[:travel_id]).destroy!
    @travel = Travel.find(params[:travel_id])
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_travel, only: %i[edit update destroy] #before_action :set_travelで各アクションの前に実行するメソッドを指定できる

  def index
    # continentのパラメータが異常な場合は無視するように設定
    if Settings.continent.keys.map(&:to_s).include?(params[:continent])
      # where 条件に合ったデータを全部取得
      @travels = Travel.where(continent: params[:continent]).order(:id).page(params[:page]).per(3)
      # areaのパラメータが異常な場合は無視するように設定
    elsif Settings.area.keys.map(&:to_s).include?(params[:area])
      @travels = Travel.where(area: params[:area]).order(:id).page(params[:page]).per(3)
    else
      @travels = Travel.order(:id).page(params[:page]).per(3)
    end
    # ユーザーがサインインしていたらお気に入り機能が使えるようになる。
    if user_signed_in?
      @favorited_travel_ids = current_user.favorites.pluck(:travel_id)
    end
  end

  def new
    @travel = Travel.new
    @travel.travel_details.build
  end

  def create
    travel = current_user.travels.create!(travel_params)
    redirect_to travel #投稿詳細ページにリダイレクト
  end

  def show
    @travel = Travel.find(params[:id]) #params[:id]はURLのpost/:idの:idに対応する数
    @travel_details = @travel.travel_details.order(:id)
  end

  def edit
    @travel_details = @travel.travel_details.order(:id)
  end

  def update
    @travel.update!(travel_params)
    redirect_to @travel
  end

  def destroy
    @travel.destroy!
    redirect_to @travel
  end

  private

  def set_travel
    @travel = current_user.travels.find_by(id: params[:id])
  end

  def travel_params
    params.require(:travel).permit(:country, :region, :city, :travel_plan, travel_details_attributes: [:id, :image, :content, :_destroy])
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create

  def check_guest
    # downcaseは小文字に変換
    if params[:user][:email].downcase == "guest@example.com"
      redirect_to root_path, alert: "ゲストユーザーの変更・削除はできません。"
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[updata destroy]
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/views/favorites/create.js.erb
document.getElementById('travel-<%= @travel.id %>').innerHTML = '<%= j render("travels/favorite", travel: @travel) %>'

app/views/favorites/destroy.js.erb
document.getElementById('travel-<%= @travel.id %>').innerHTML = '<%= j render("travels/disfavorite", travel: @travel) %>'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ENJOY TRIP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="fixed-top bg-black">
  <nav class="navbar navbar-expand navbar-dark navbar-header" >
    <ul class="navbar-nav mr-auto">
      <%= link_to "ENJOY TRIP", travels_path, class: 'navbar-brand' %>
    </ul>
    <% if user_signed_in? || !devise_controller? %>
      <div class="dropdown">
        <button class="btn-header mr-4" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
          <i class="fas fa-user-circle fa-2x text-white"></i>
        </button>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
          <% if user_signed_in? %>
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            <%= link_to 'アカウント編集', edit_user_registration_path, class: 'dropdown-item' %>
            <%= link_to "新規投稿", new_travel_path, class: "dropdown-item" %>
          <% else %>
            <%= link_to "新規登録", new_user_registration_path, class: 'dropdown-item' %>
            <%= link_to "ログイン", new_user_session_path, class: 'dropdown-item' %>
            <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, class: 'dropdown-item', method: :post %>
          <% end %>
        </div>
      </div>
    <% end %>
    <div id="Navber">
      <ul class="navbar-nav">
        <% if user_signed_in? || !devise_controller? %>
          <li class="navbar-nav active">
            <%= link_to href="#", class: 'nav-link' do %>
              <button type="button" class="btn-header" data-toggle="modal" data-target="#mapModal" >
                <i class="fas fa-search fa-2x text-white"></i>
              </button>
            <% end %>
          </li>
        <% end %>
        <% unless user_signed_in? %>
          <% if request.path == "/users/sign_in" %>
            <li class="nav-item active">
              <span class="nav-link text-brown yet-member">
                まだ会員<br class="header-br">でない方
              </span>
            </li>
            <li class="nav-item active nav-new" >
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-white' %>
            </li>
          <% elsif request.path == "/users/sign_up" %>
            <li class="nav-item active ">
              <span class="nav-link text-brown">
                既に会員の方
              </span>
            </li>
            <li class="nav-item active nav-login">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-white'%>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </nav>
</header>
<%= render 'shared/map_modal' %>

app/views/shared/_map_modal.html.erb
<div class="modal fade" id="mapModal" tabindex="-1" role="dialog" aria-labelledby="mapModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title modal-string" id="mapModalLabel">エリアから探す</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="modal-string">
          <p>海外から探す ></p>
        </div>
        <div class="map-image-wrapper">
          <%= image_tag "/images/world_map.jpg", class: "map-image" %>
          <% Settings.continent.keys.map(&:to_s).each do |continent| %>
            <div class="map-area map-<%= continent %>">
              <%= link_to  travels_path(continent: continent), class: "map-area map-#{continent}" do %>
                <i class="fas fa-map-marker-alt color"></i> <%= Settings.continent.send(continent) %>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="modal-string">
          <p>国内から探す ></p>
        </div>
        <div class="map-image-wrapper">
          <%= image_tag "/images/japan_map.jpg", class: "map-image" %>
          <% Settings.area.keys.map(&:to_s).each do |area| %>
            <div class="map-area map-<% area %>">
              <%= link_to travels_path(area: area), class: "map-area map-#{area}" do %>
                <i class="fas fa-map-marker-alt color"></i> <%= Settings.area.send(area) %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <%= link_to "投稿一覧", travels_path, class: "list" %>
        <button type="button" class="btn-header" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/travels/_disfavorite.html.erb
<%= link_to travel_favorites_path(travel), method: :post, remote: true do %>
  <i class="fas fa-star disfavorite-btn "></i>
<% end %>
<%= travel.favorites_count %>

app/views/travels/_favorite.html.erb
<%= link_to travel_favorites_path(travel), method: :delete, remote: true do %>
  <i class="fas fa-star favorite-btn "></i>
<% end %>
<%= travel.favorites_count %>

app/views/travels/_form.html.erb
<%= form_with model: @travel, local: true, id: "travel-form" do |form| %>
  <div class="form-group">
    <%= form.label :country, "国名" , class: "font-size" %>
    <%= form.text_field :country, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :region, "地域" , class: "font-size" %>
    <%= form.text_field :region, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :city, "都市", class: "font-size" %>
    <%= form.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :travel_plan, "旅行プラン" , class: "font-size" %>
    <%= form.text_area :travel_plan, class: "form-control", rows: 2 %>
  </div>
  <p>
    <%= form.fields :travel_details, model: @travel_details do |travel_detail| %>
      <% render "travel_detail_fields", f: travel_detail %>
    <% end %>
  </p>
  <p>
    <%= link_to_add_association "＋ 写真とコメントを追加", form, :travel_details, class: "image-content"  %>
  </p>
  <p><%= form.submit "送信" , class: "send" %></p>
<% end %>

app/views/travels/_travel_detail_fields.html.erb
<div class="nested-fields">
  <%= f.hidden_field :_destroy %>
    <div class="form-group">
    <%= f.label :image, "写真" , class: "string-margin font-size" %>
    <%= f.file_field :image, data: { image_url: f.object.image.url } %>
  </div>
  <div class="form-group">
    <%= f.label :content, "コメント" , class: "font-size" %>
    <%= f.text_area :content, class: "form-control form-control-width", rows: 6 %>
  </div>
  <%= link_to_remove_association "削除", f , class: "new-post-remove" %>
</div>

app/views/travels/edit.html.erb
<div class="container-post">
  <h1 class="text-center">編集</h1>
  <%= render "form" %> <%# 部分テンプレート%>
</div>

app/views/travels/index.html.erb
<%# continentのパラメータが異常な場合は無視するように設定 %>
<% if Settings.continent.keys.map(&:to_s).include?(params[:continent]) %>
  <div class="top-image">
    <%= image_tag "/images/#{params[:continent]}.jpg", style: "width: 100%" %>
    <%# Settings.continent.sendは文字列を呼び出すためのメソッド %>
    <div class="text"><%= Settings.continent.send(params[:continent]) %></div>
  </div>
  <%# areaのパラメータが異常な場合は無視するように設定 %>
<% elsif Settings.area.keys.map(&:to_s).include?(params[:area]) %>
  <div class="top-image">
    <%= image_tag "/images/#{params[:area]}.jpg", style: "width: 100%" %>
    <div class="text"><%= ("#{Settings.area.send(params[:area])}地方") %></div>
  </div>
<% else %>
  <div class="slider">
    <%= image_tag "/images/app-top-image.jpg" %>
    <%= image_tag "/images/stockholm.jpg" %>
    <%= image_tag "/images/gamla-stan.jpg" %>
    <%= image_tag "/images/swiss.jpg" %>
    <%= image_tag "/images/tekapo.jpg" %>
  </div>
<% end %>
<div class="report">
  <% @travels.each do |travel| %>
    <hr width="80%" noshade>
    <div class="box-container">
      <div class="box-img">
        <p><%= image_tag travel.travel_details.order(:id).first.image.url, width: 300 %></p>
      </div>
      <div class="box-text">
        <p><%= l travel.created_at, format: :short %></p>
        <p><%= travel.country %></p>
        <p><%= travel.region %></p>
        <% if user_signed_in? %>
          <p id="travel-<%= travel.id %>">
            <% if @favorited_travel_ids.include?(travel.id) %>
              <%= render "favorite", travel: travel %>
            <% else %>
              <%= render "disfavorite", travel: travel %>
            <% end %>
          </p>
        <% end %>
        <p>
          <%= link_to "詳細", travel , class: "detail" %>
          <% if user_signed_in? && current_user.id == travel.user.id %>
            <%= link_to "編集", edit_travel_path(travel), class: "edit" %>
            <%= link_to "削除", travel_path(travel), method: :delete, data: { confirm: "削除しますか?" } , class: "remove" %>
          <% end %>
        </p>
      </div>
    </div>
  <% end %>
  <%= paginate @travels %>
</div>

app/views/travels/new.html.erb
<div class="container-post">
<h1 class="text-center">新規投稿</h1>
<%= render "form" %>
</div>

app/views/travels/show.html.erb
<div class="slider">
  <%= image_tag "/images/passport.jpg"%>
  <%= image_tag "/images/plane.jpg"%>
  <%= image_tag "/images/road.jpg"%>
  <%= image_tag "/images/train.jpg"%>
  <%= image_tag "/images/fika.jpg"%>
</div>
<div class="container-post">
  <div class="string-font my-1">
    <p><%= l @travel.created_at, format: :short %></p>
    <p><%= @travel.country %></p>
    <p><%= @travel.region %></p>
    <p><%= @travel.city %></p>
    <%= simple_format(h @travel.travel_plan) %></p>
</div>
<div id='map'></div>
<% @travel_details.each do |travel_detail| %>
  <p><%= image_tag travel_detail.image.url, width: 600, class: "travel-detils-image" %></p>
  <div class="content-detail">
    <%= simple_format(h travel_detail.content) %>
  </div>
<% end %>
<% if user_signed_in? %>
  <p id="travel-<%= @travel.id%>">
    <% if @travel.favorited_by?(current_user) %>
      <%= render "favorite", travel: @travel %>
    <% else %>
      <%= render "disfavorite", travel: @travel %>
    <% end %>
  </p>
<% end %>
<% if user_signed_in? && current_user.id == @travel.user.id %>
  <p>
    <%= link_to "編集", edit_travel_path(@travel), class: "list-edit" %>
    <%= link_to "削除", travel_path(@travel), method: :delete, data: { confirm: "削除しますか?" }, class: "list-remove" %>
  </p>
<% end %>
<p><%= link_to "投稿一覧", travels_path, class: "list-post" %></p>
</div>
<script>
  let map
  
  function initMap() {
    geocoder = new google.maps.Geocoder()
  
    map = new google.maps.Map(document.getElementById('map'), {
      center: { lat: <%= @travel.latitude %>, lng: <%= @travel.longitude %>},
  zoom: 12,
            });
  
  marker = new google.maps.Marker({
    position: { lat: <%= @travel.latitude %>, lng: <%= @travel.longitude %>},
  map: map
            });
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google[:map][:api] %>&callback=initMap" async defer></script>